server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_ecommerce
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect